# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rY_hFD8GFYVyFg_BC_fdmmAP4sjjRX-P
"""

numero = 23

numero == 23

numero != 23

numero < 50

numero > 50

numero <= 50

numero >= 50

"""# Fluxo de controles no python 
É a capacidade que todo programa tem de decidir qual código executar primeiro

Controle de fluxo em python
>>> if
>>> elif
>>> else
>>> for 
>>> while
"""

numero = 23

# condiçaõ 1
if numero > 10:
    print("Este numero é maior de 10")
# condição 2
else:
    print("Numero menor que 23")

# Fábrica de carros lataria / motor / rodas

1 - lataria
    1 - fabricar peças da lataria
    2 - fabricar parafusos
    3 - pintura da lataria

2 - motor
    1 - fabricalçao de peças
    2 - colocação de parafusos
    3 -  montagem das peças
    4 - montagem do reservatório

3 - rodas
    1 - modar as rodas
    2 -  colocar frisos
    3 - teste de durabulidade

# in / not / end 
numero = [1,2,3,7,10]

if 1 in numero:
    if True:
        # Código aninhado, identação aninhada
        if True:
            numero_1 = 1+1
            print(numero_1)
        else:
            print("Este numero não esta na lista")
        numero_1 = 1+1
        print(numero_1)        
    else:
        print("Este numero não esta na lista")

elif 12 in numero:
    numero_2 = 2+2
    print(numero_2)
elif 13 in numero:
    numero_3 = 3+3
    print(numero_3)
else:
    print("Este numero não esta contido na lista")



"""# Tiago no Python"""

idade = [5, 10, 12, 18]
idades_permitidas = 18

if idades_permitidas in idade:
    if 18 in idade:
        print("Ok, você maior de 18 pode entrar os outros não!")
    print("Vocês querem entrar em uma festa proíbida para menores de 18!")

else:
    print("não permitido")

"""# for / while

# Funções do python para revisar

1 - print()
2 - len()
3 - input()
4 - int()
5 - float()
6 - str()
7 - type()
8 - map()
9 - reduce()
10 - range()

## Trazer um pequeno resumo das funçoes em python >>> próxima aula
"""